language: scala
sudo: false
jdk: oraclejdk8
addons:
  apt:
    packages:
      - lib32stdc++6
script:
  - sbt isabelleBuild
env:
  matrix:
    - ISABELLE_VERSION=2016
    - ISABELLE_VERSION=2016-1
    - ISABELLE_VERSION=2017
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.isabelle
    - $HOME/.local/share/libisabelle
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
